Updated to ubiquity 2.18.8 base

diff --git a/d-i/source/grub-installer/grub-installer b/d-i/source/grub-installer/grub-installer
--- a/d-i/source/grub-installer/grub-installer
+++ b/d-i/source/grub-installer/grub-installer
@@ -170,7 +170,7 @@ hurd_convert () {
 # This should probably be rewritten using udevadm or similar.
 device_to_disk () {
 	echo "$1" | \
-		sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[hs]d[0-9]\+\|/dev/[a-z]\+\).*:\1:'
+		sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/nvme[0-9]n[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[hs]d[0-9]\+\|/dev/[a-z]\+\).*:\1:'
 }
 
 # Run update-grub in $ROOT
@@ -181,8 +181,8 @@ update_grub () {
 	else
 		in_target="log-output -t grub-installer $chroot $ROOT"
 	fi
-	if ! $in_target $update_grub; then
-		error "Running '$update_grub' failed." 1>&2
+	if ! $in_target $update_grub_cmd; then
+		error "Running '$update_grub_cmd' failed." 1>&2
 		db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
 		db_go || true
 		db_progress STOP
@@ -324,7 +324,7 @@ case $prefix in
     /dev/loop)
 	disc_offered_devfs="$bootfs"
 	;;
-    /dev/[hsv]d[a-z0-9]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*)
+    /dev/[hsv]d[a-z0-9]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*|/dev/fio[a-z]|/dev/nvme[0-9]n[0-9])
 	disc_offered_devfs="$prefix"
 	;;
     *)
@@ -437,17 +437,26 @@ case $ARCH in
 	fi
 	;;
     i386/efi|amd64/efi)
-	sb_var=/sys/firmware/efi/vars/SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c/data
-	if [ "$ARCH" = amd64/efi ] && [ -e "$sb_var" ] && \
-	   [ "$(printf %x \'"$(cat "$sb_var")")" = 1 ]; then
+	if [ "$ARCH" = amd64/efi ]; then
 		grub_package="grub-efi-amd64-signed"
 	else
 		grub_package="grub-efi"
+	fi
+	if [ ! -d /target/boot/efi ]; then
+		# No EFI System Partition, so presumably the partitioner
+		# believed this to be unnecessary, perhaps because we're
+		# installing on a pre-existing MBR partition table or
+		# perhaps because there's a BIOS Boot Partition.  In either
+		# case, the right answer is to fall back to grub-pc.
+		grub_package="grub-pc"
 	fi
 	;;
     powerpc/*)
 	grub_package="grub-ieee1275"
 	experimental_arch
+	;;
+    ppc64el/*)
+	grub_package="grub-ieee1275"
 	;;
     mipsel/loongson-2f)
 	grub_package="grub-yeeloong"
@@ -472,14 +481,14 @@ case $grub_package in
     grub)
 	grub_version="grub"
 	menu_file="menu.lst"
-	update_grub="update-grub -y"
+	update_grub_cmd="update-grub -y"
 	partition_offset=1
 	frgrubroot=$(($frgrubroot - 1))
 	;;
     *)
 	grub_version="grub2"
 	menu_file="grub.cfg"
-	update_grub="update-grub"
+	update_grub_cmd="update-grub"
 	partition_offset=0
 	;;
 esac
@@ -559,12 +568,6 @@ case "$grub_package" in
 		apt-install $grub_package || exit_code=$? 
 	fi
 	;;
-    grub-efi)
-     log-output -t grub-installer-lm $chroot $ROOT dpkg -i /usr/share/local-repository/binary/efibootmgr_*_amd64.deb \
-                         /usr/share/local-repository/binary/grub-efi_*_amd64.deb\
-                         /usr/share/local-repository/binary/grub-efi-amd64_*_amd64.deb\
-                         /usr/share/local-repository/binary/grub-efi-amd64-bin_*_amd64.deb || exit_code=$?
-     ;;
    *)
 	# Will pull in os-prober based on global setting for Recommends
 	apt-install $grub_package || exit_code=$? 
@@ -674,6 +677,9 @@ fi
 default_bootdev_os="$($chroot $ROOT grub-mkdevicemap --no-floppy -m - | head -n1 | cut -f2)"
 if [ "$default_bootdev_os" ]; then
 	default_bootdev="$($chroot $ROOT readlink -f "$default_bootdev_os")"
+	if db_get grub-installer/bootdev && [ "$RET" = '(hd0)' ]; then
+		db_set grub-installer/bootdev "$default_bootdev"
+	fi
 else
 	default_bootdev="(hd0)"
 fi
@@ -723,7 +729,7 @@ case $ARCH:$grub_package in
 			  sed 's:\(/dev/\(cciss\|ida\|rs\)/c[0-9]d[0-9][0-9]*\|/dev/mmcblk[0-9]\|/dev/\(ad\|da\)[0-9]\+\|/dev/[a-z]\+\).*:\1:')
 			disks="${disks:+$disks }$prefix"
 			case $prefix in
-			    /dev/[hsv]d[a-z]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*)
+			    /dev/[hsv]d[a-z]|/dev/xvd[a-z]|/dev/cciss/c[0-9]d[0-9]*|/dev/ida/c[0-9]d[0-9]*|/dev/rs/c[0-9]d[0-9]*|/dev/mmcblk[0-9]|/dev/ad[0-9]*|/dev/da[0-9]*|/dev/fio[a-z]|/dev/nvme[0-9]n[0-9])
 				if [ "$prefix" != "$frdisk_one" ]; then
 					use_disks=1
 				fi
@@ -741,6 +747,10 @@ case $ARCH:$grub_package in
 		db_set grub-installer/bootdev "$default_bootdev"
 	fi
 	;;
+    ppc64el/*:grub-ieee1275)
+	bootdev="$(/usr/lib/grub-installer/prep-bootdev)"
+	state=3
+	;;
     *)
 	# No need for install device selection on other platforms.
 	bootdev=dummy
@@ -752,7 +762,11 @@ db_progress STEP 1
 db_progress INFO grub-installer/progress/step_bootdev
 
 while : ; do
-	if [ "$state" = 1 ]; then
+	db_fget grub-installer/bootdev seen
+	if [ "$RET" = true ] && db_get grub-installer/bootdev && [ "$RET" ] ; then
+		bootdev=$RET
+		break
+	elif [ "$state" = 1 ]; then
 		if [ "$frdev" ]; then
 			# If /boot is on SATA RAID/multipath, then there's
 			# only one possible answer; we don't support device
@@ -871,9 +885,16 @@ if [ -z "$frdisk" ] || [ "$grub_version" = grub2 ]; then
 			grub_install_params="$grub_install_params --force"
 		fi
 
+		case $ARCH:$grub_package in
+		    ppc64el/*:grub-ieee1275)
+			info "Wiping PReP partition $bootdev"
+			log-output -t grub-installer dd if=/dev/zero of="$bootdev" bs=512 count="$(blockdev --getsz "$bootdev")"
+			;;
+		esac
+
 		CODE=0
 		case $ARCH:$grub_package in
-		    *:grub|*:grub-pc|sparc:grub-ieee1275)
+		    *:grub|*:grub-pc|sparc:grub-ieee1275|ppc64el/*:grub-ieee1275)
 			info "Running $chroot $ROOT grub-install $grub_install_params \"$bootdev\""
 			log-output -t grub-installer $chroot $ROOT grub-install $grub_install_params "$bootdev" || CODE=$?
 			;;
@@ -886,7 +907,7 @@ if [ -z "$frdisk" ] || [ "$grub_version" = grub2 ]; then
 			info "grub-install ran successfully"
 		else
 			case $ARCH:$grub_package in
-			    *:grub|*:grub-pc|sparc:grub-ieee1275)
+			    *:grub|*:grub-pc|sparc:grub-ieee1275|ppc64el/*:grub-ieee1275)
 				error "Running 'grub-install $grub_install_params \"$bootdev\"' failed."
 				;;
 			    *)
@@ -942,7 +963,7 @@ split_device () {
 	disk=
 	part=
 	case $1 in
-		/dev/[vhs]d[a-z]*)
+		/dev/[vhs]d[a-z]*|/dev/fio[a-z]*)
 			disk="$(echo "$1" | sed 's,\(/dev/[a-z]\+\).*,\1,')"
 			part="$(echo "$1" | sed 's,/dev/[a-z]\+\(.*\),\1,')"
 			;;
@@ -954,6 +975,11 @@ split_device () {
 		/dev/mmcblk*)
 			disk="$(echo "$1" | sed 's,\(/dev/mmcblk[0-9]\+\).*,\1,')"
 			part="$(echo "$1" | sed 's,/dev/mmcblk[0-9]\+p\([0-9]\+\),\1,')"
+			[ "$part" != "$1" ] || part=
+			;;
+		/dev/nvme*n*)
+			disk="$(echo "$1" | sed 's,\(/dev/nvme[0-9]\+n[0-9]\+\).*,\1,')"
+			part="$(echo "$1" | sed 's,/dev/nvme[0-9]\+n[0-9]\+p\([0-9]\+\),\1,')"
 			[ "$part" != "$1" ] || part=
 			;;
 	esac
